### ISSUE TITLE
Non-responsive Slicer on close if there is an active OpenIGTLinkIF connector

### ISSUE THREAD

**Issue by jamesobutler** [openigtlink/SlicerOpenIGTLink#57]
Windows 7
Slicer 4.9.0-2018-08-17

If I open Slicer and go to OpenIGTLinkIF module, add an IGTLConnector and set the status to Active, then close Slicer, Slicer will become unresponsive on close displaying a vtkOutputWindow with the following messages:

````
Generic Warning: In D:\D\P\Slicer-0-build\VTKv9\Common\Core\vtkDebugLeaks.cxx, line 281
Deleting unknown object: vtkMRMLNodeSequencer
````

**Comment by jamesobutler** [comment]
Apologies, after coming back to this it appears that vtkMRMLNodeSequencer is introduced with the [Sequences](https://github.com/SlicerRt/Sequences) extension. After uninstalling the Sequences extension, following the steps listed in my original post resulted in no Slicer issues when closing.

However, this issue has so far only presented itself when doing the steps stated in the original message with the Sequences extension also being installed.  Maybe there is an issue with how the SlicerOpenIGTLink extension is handling removing nodes on close? Or maybe an issue with how the Sequences extension is handling removing other nodes on close?  I have been unable to recreate this issue when strictly using the Sequences extension.

I don't have a Slicer-build right now on my Windows 7 machine to debug this further beyond what output I see using the Slicer-nightly binary.

**Comment by Sunderlandkyl** [comment]
I actually have recently experienced this problem.

It's interesting because it only happens on some computers. Sequences doesn't seem to be a factor as far as I can tell.

I couldn't get a debug build to cause the issue on my computer, but I tested a nightly build on a different computer that has the issue and it looks like it's an issue with the igtlioConnector not terminating correctly.

I'll take a closer look at it.
